// src/lib/guidelines-data.ts
import { Guideline } from "./types";

export const guidelines: Guideline[] = [
  {
    title: "Comprehensive Intraoperative Multiplane TEE",
    organization: "ASE / SCA",
    year: 2013,
    description: "Defines the 28-view comprehensive TEE examination.",
    tags: ["TEE", "28 Views"],
    filename: "ase-sca-2013-comprehensive-tee.pdf",
  },
  {
    title: "Basic Perioperative TEE Exam",
    organization: "ASE / SCA",
    year: 2013,
    description: "Defines the 11-view basic perioperative TEE examination.",
    tags: ["TEE", "Basic Exam"],
    filename: "ase-sca-2013-basic-tee.pdf",
  },
  {
    title: "Cardiac Chamber Quantification",
    organization: "ASE / EACVI",
    year: 2015,
    description: "Normal values for all cardiac chambers.",
    tags: ["Normal Values", "LV", "RV"],
    filename: "ase-2015-chamber-quantification.pdf",
  },
  {
    title: "Management of Valvular Heart Disease",
    organization: "AHA / ACC",
    year: 2020,
    description: "Classification and management of all valve diseases.",
    tags: ["Valve Disease", "AS", "MR"],
    filename: "aha-acc-2020-valvular-heart-disease.pdf",
  },
  {
    title: "LV Diastolic Function Evaluation",
    organization: "ASE / EACVI",
    year: 2016,
    description: "Diastolic function algorithm: E/A, e\u2019, E/e\u2019, TR velocity.",
    tags: ["Diastolic Function"],
    filename: "ase-2016-diastolic-function.pdf",
  },
  {
    title: "Echocardiographic Assessment of the Right Heart",
    organization: "ASE",
    year: 2010,
    description: "RV function: TAPSE, FAC, S\u2019, RV strain.",
    tags: ["Right Heart", "TAPSE"],
    filename: "ase-2010-right-heart.pdf",
  },
  {
    title: "TEE in Noncardiac Surgery",
    organization: "SCA / ASE",
    year: 2020,
    description: "Expanding indications for intraoperative TEE.",
    tags: ["Noncardiac Surgery"],
    filename: "sca-2020-tee-noncardiac.pdf",
  },
  {
    title: "Standardized Reporting of Echo Findings",
    organization: "ASE",
    year: 2025,
    description: "Newest ASE guideline \u2014 standardized echo reports.",
    tags: ["Reporting", "Newest"],
    filename: "ase-2025-standardized-reporting.pdf",
  },
  {
    title: "Native Valvular Regurgitation Evaluation",
    organization: "ASE",
    year: 2017,
    description: "PISA, vena contracta, EROA, regurgitant volume.",
    tags: ["MR", "AR", "PISA"],
    filename: "ase-2017-valvular-regurgitation.pdf",
  },
  {
    title: "Algorithmic MV Assessment (BIDMC)",
    organization: "BIDMC Research",
    year: 2022,
    description: "Stepwise MV assessment \u2014 Carpentier classification.",
    tags: ["Mitral Valve", "Carpentier"],
    filename: "bidmc-2022-mv-assessment.pdf",
  },
];
